import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { BookOpen } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Navbar />
      <main className="flex-1 container mx-auto px-4 py-16 max-w-4xl">
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-muted text-muted-foreground rounded-full text-sm font-semibold mb-6">
             <BookOpen className="w-4 h-4" /> Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-bold font-heading mb-4">Terms of Service</h1>
          <p className="text-xl text-muted-foreground leading-relaxed">
            Effective Date: April 18, 2026.
          </p>
        </div>

        <div className="space-y-8 text-muted-foreground leading-relaxed">
          
          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using HireDx ("the Platform"), you agree to be bound by these Terms of Service. This platform is built as an official submission for the DevClash 2026 Hackathon (PS6: Interview Rejection Analysis System).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground mb-3">2. Description of Service</h2>
            <p>
              HireDx utilizes Google generative AI (Gemini 2.5 Flash-Lite) to analyze user-uploaded interview recordings. The platform delivers programmatic feedback including speech analytics, behavioral evaluations, and automated improvement plans. We do not guarantee employment or interview passage.
            </p>
          </section>

          <section>
             <h2 className="text-xl font-bold text-foreground mb-3">3. User Responsibilities & Consent</h2>
             <p>
               You must ensure that you have legal consent to record and upload any audio or video files. Do not upload classified, proprietary, or highly sensitive corporate information. You maintain all intellectual property rights to your uploads.
             </p>
          </section>

          <section>
             <h2 className="text-xl font-bold text-foreground mb-3">4. Limitation of Liability</h2>
             <p>
               Because the analysis is generated by an Artificial Intelligence, it may occasionally produce inaccurate, misleading, or poorly contextualized advice. HireDx and its developers shall not be held liable for any damages, missed employment opportunities, or distress caused by the usage of this platform.
             </p>
          </section>

        </div>
      </main>
      <Footer />
    </div>
  );
}
